//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("JsonExSerializer")]
[assembly: AssemblyDescription(".NET Serialization Framework using JSON")]
[assembly: AssemblyProduct("JsonExSerializer")]
[assembly: AssemblyCopyright("Copyright © 2007")]
[assembly: ComVisible(false)]
[assembly: Guid("12d697c6-ebf8-479f-b78a-86fdf09307d0")]
[assembly: AssemblyInformationalVersion("1.0")]
[assembly: AssemblyVersion("1.0.0.62")]
[assembly: AssemblyFileVersion("1.0.0.62")]


