using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("JsonExSerializerTests")]
[assembly: AssemblyDescriptionAttribute(".NET Serialization Framework Tests using JSON")]
[assembly: AssemblyProductAttribute("JsonExSerializer")]
[assembly: AssemblyCopyrightAttribute("Copyright � 2007")]
[assembly: ComVisibleAttribute(false)]
[assembly: GuidAttribute("041b67d7-8bf6-4867-ba57-bc8dc556cbc6")]
[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyInformationalVersionAttribute("3.0 Alpha 1")]
[assembly: AssemblyVersionAttribute("3.0.309.198")]
[assembly: AssemblyFileVersionAttribute("3.0.309.198 Alpha 1")]
//[assembly: AssemblyKeyFile(@"..\..\..\JsonExSerializer.snk")]