using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("JsonExSerializer")]
[assembly: AssemblyDescriptionAttribute(".NET Serialization Framework using JSON")]
[assembly: AssemblyProductAttribute("JsonExSerializer")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2007")]
[assembly: ComVisibleAttribute(false)]
[assembly: GuidAttribute("12d697c6-ebf8-479f-b78a-86fdf09307d0")]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyInformationalVersionAttribute("3.01")]
[assembly: AssemblyVersionAttribute("3.01.148.219")]
[assembly: AssemblyFileVersionAttribute("3.01.148.219")]
[assembly: InternalsVisibleTo("JsonExSerializerTests, PublicKey=0024000004800000940000000602000000240000525341310004000001000100BBF047AD3730235423C19BBAB2B5321DE1C8422E784080BAB25113E8833EF01AB44F19D5DD023E7F4625F4423F205C85CB049A0061FABD730AC2713E41D655D8C83C0BECA70D0A74168A601FC30957AF5FAA893EE7A0594561AA29DF9D1F9504F3B09C25ED1374168117DD13A9BF618DA7DA5CC311450B598D8D7B1B65240CC3")]
