using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("JsonExSerializer")]
[assembly: AssemblyDescriptionAttribute(".NET Serialization Framework using JSON")]
[assembly: AssemblyProductAttribute("JsonExSerializer")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2007")]
[assembly: ComVisibleAttribute(false)]
[assembly: GuidAttribute("12d697c6-ebf8-479f-b78a-86fdf09307d0")]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyInformationalVersionAttribute("2.0")]
[assembly: AssemblyVersionAttribute("2.0.0.100")]
[assembly: AssemblyFileVersionAttribute("2.0.0.100")]

