using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("PerformanceTests")]
[assembly: AssemblyDescriptionAttribute(".NET Serialization Framework Performance Tests using JSON")]
[assembly: AssemblyProductAttribute("JsonExSerializer")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2007")]
[assembly: ComVisibleAttribute(false)]
[assembly: GuidAttribute("0464792e-0155-4baf-ba64-cb2ea4843097")]
[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyInformationalVersionAttribute("2.1")]
[assembly: AssemblyVersionAttribute("2.1.1.144")]
[assembly: AssemblyFileVersionAttribute("2.1.1.144")]

