//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("JsonExSerializerTests")]
[assembly: AssemblyDescription(".NET Serialization Framework Tests using JSON")]
[assembly: AssemblyProduct("JsonExSerializer")]
[assembly: AssemblyCopyright("Copyright © 2007")]
[assembly: ComVisible(false)]
[assembly: Guid("041b67d7-8bf6-4867-ba57-bc8dc556cbc6")]
[assembly: AssemblyInformationalVersion("1.1")]
[assembly: AssemblyVersion("1.1.0.66")]
[assembly: AssemblyFileVersion("1.1.0.66")]


